# Generated by Django 5.1.1 on 2024-10-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0025_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
